import { Listing, ListingWithAuthor, User } from "@/types";

export const mockUser: User = {
  id: "user-1",
  name: "John Doe",
  email: "john@example.com",
  createdAt: new Date("2024-01-15"),
};

export const mockListings: ListingWithAuthor[] = [
  {
    id: "1",
    title: "Sunset Safari in Serengeti",
    description:
      "Experience the magic of an African sunset while observing wildlife in their natural habitat. Our expert guides will take you through the Serengeti National Park, home to lions, elephants, zebras, and countless other species. This unforgettable 4-hour safari includes a sundowner stop at a scenic viewpoint.",
    location: "Serengeti National Park, Tanzania",
    price: 250,
    imageUrl: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
    category: "Adventure",
    duration: "4 hours",
    maxGuests: 6,
    userId: "user-1",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-10"),
    author: {
      id: "user-1",
      name: "Safari Adventures Co",
      email: "contact@safariadventures.com",
    },
  },
  {
    id: "2",
    title: "Traditional Japanese Tea Ceremony",
    description:
      "Immerse yourself in the ancient art of the Japanese tea ceremony. Learn about the centuries-old traditions, etiquette, and philosophy behind this meditative practice. Enjoy authentic matcha tea and traditional sweets in a beautiful tea house in Kyoto's historic district.",
    location: "Kyoto, Japan",
    price: 85,
    imageUrl: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80",
    category: "Culture",
    duration: "2 hours",
    maxGuests: 8,
    userId: "user-2",
    createdAt: new Date("2024-03-09"),
    updatedAt: new Date("2024-03-09"),
    author: {
      id: "user-2",
      name: "Kyoto Cultural Experiences",
      email: "info@kyotoculture.jp",
    },
  },
  {
    id: "3",
    title: "Scuba Diving in Great Barrier Reef",
    description:
      "Dive into the world's largest coral reef system and explore the underwater world with professional guides. Suitable for beginners and experienced divers. All equipment included. Witness colorful coral formations, tropical fish, sea turtles, and maybe even reef sharks!",
    location: "Cairns, Australia",
    price: 180,
    imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80",
    category: "Adventure",
    duration: "Full day",
    maxGuests: 10,
    userId: "user-3",
    createdAt: new Date("2024-03-08"),
    updatedAt: new Date("2024-03-08"),
    author: {
      id: "user-3",
      name: "Reef Explorers",
      email: "dive@reefexplorers.com.au",
    },
  },
  {
    id: "4",
    title: "Italian Cooking Class in Tuscany",
    description:
      "Learn to make authentic Italian cuisine from a local chef in the heart of Tuscany. We'll prepare fresh pasta, traditional sauces, and classic desserts using ingredients from our own garden. Enjoy wine from local vineyards as you cook and dine al fresco.",
    location: "Florence, Italy",
    price: 120,
    imageUrl: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=80",
    category: "Food",
    duration: "5 hours",
    maxGuests: 12,
    userId: "user-4",
    createdAt: new Date("2024-03-07"),
    updatedAt: new Date("2024-03-07"),
    author: {
      id: "user-4",
      name: "Nonna's Kitchen",
      email: "cook@nonnaskitchen.it",
    },
  },
  {
    id: "5",
    title: "Northern Lights Photography Tour",
    description:
      "Chase the Aurora Borealis with expert photographers who know the best locations and techniques. We provide professional camera equipment if needed and teach you how to capture stunning photos of this natural phenomenon. Includes hot drinks and warm clothing.",
    location: "Tromsø, Norway",
    price: 200,
    imageUrl: "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=800&q=80",
    category: "Nature",
    duration: "6 hours",
    maxGuests: 8,
    userId: "user-5",
    createdAt: new Date("2024-03-06"),
    updatedAt: new Date("2024-03-06"),
    author: {
      id: "user-5",
      name: "Arctic Light Expeditions",
      email: "tours@arcticlight.no",
    },
  },
  {
    id: "6",
    title: "Bali Yoga & Meditation Retreat",
    description:
      "Find your inner peace with daily yoga sessions overlooking rice terraces. This retreat includes meditation, healthy vegetarian meals, and spa treatments. Perfect for beginners and experienced yogis looking to deepen their practice in a serene environment.",
    location: "Ubud, Bali, Indonesia",
    price: 150,
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80",
    category: "Wellness",
    duration: "3 days",
    maxGuests: 15,
    userId: "user-6",
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-05"),
    author: {
      id: "user-6",
      name: "Bali Serenity Retreats",
      email: "info@baliserenity.com",
    },
  },
  {
    id: "7",
    title: "Surfing Lessons in Hawaii",
    description:
      "Learn to surf on the famous North Shore of Oahu with certified instructors. Whether you're a complete beginner or looking to improve your technique, we tailor lessons to your skill level. Small group sizes ensure personalized attention. All equipment provided.",
    location: "Oahu, Hawaii",
    price: 95,
    imageUrl: "https://images.unsplash.com/photo-1502933691298-84fc14542831?w=800&q=80",
    category: "Sports",
    duration: "3 hours",
    maxGuests: 6,
    userId: "user-7",
    createdAt: new Date("2024-03-04"),
    updatedAt: new Date("2024-03-04"),
    author: {
      id: "user-7",
      name: "Aloha Surf School",
      email: "surf@alohasurf.com",
    },
  },
  {
    id: "8",
    title: "Santorini Sunset Sailing",
    description:
      "Sail around the stunning caldera of Santorini on a traditional Greek boat. Watch the famous sunset while enjoying Greek wine and mezze. Swim in hot springs and explore hidden beaches. This romantic experience is perfect for couples and small groups.",
    location: "Santorini, Greece",
    price: 140,
    imageUrl: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=800&q=80",
    category: "Beach",
    duration: "5 hours",
    maxGuests: 10,
    userId: "user-8",
    createdAt: new Date("2024-03-03"),
    updatedAt: new Date("2024-03-03"),
    author: {
      id: "user-8",
      name: "Aegean Sailing",
      email: "sail@aegeansailing.gr",
    },
  },
  {
    id: "9",
    title: "Street Food Tour in Bangkok",
    description:
      "Explore Bangkok's vibrant street food scene with a local foodie guide. Taste authentic Thai dishes from the best street vendors, learn about ingredients and cooking techniques, and discover hidden gems that tourists rarely find. Vegetarian options available.",
    location: "Bangkok, Thailand",
    price: 60,
    imageUrl: "https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=800&q=80",
    category: "Food",
    duration: "4 hours",
    maxGuests: 8,
    userId: "user-9",
    createdAt: new Date("2024-03-02"),
    updatedAt: new Date("2024-03-02"),
    author: {
      id: "user-9",
      name: "Bangkok Food Adventures",
      email: "eat@bangkokfood.com",
    },
  },
  {
    id: "10",
    title: "Machu Picchu Sunrise Hike",
    description:
      "Experience the magic of Machu Picchu at sunrise before the crowds arrive. Our knowledgeable guides will share the fascinating history of the Inca civilization as you explore this UNESCO World Heritage site. Includes transportation and entrance fees.",
    location: "Cusco, Peru",
    price: 175,
    imageUrl: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&q=80",
    category: "Adventure",
    duration: "8 hours",
    maxGuests: 12,
    userId: "user-10",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
    author: {
      id: "user-10",
      name: "Inca Trail Experts",
      email: "trek@incatrail.pe",
    },
  },
  {
    id: "11",
    title: "New York City Architecture Tour",
    description:
      "Discover the architectural marvels of NYC from Art Deco skyscrapers to modern glass towers. Led by an architecture historian, this walking tour covers iconic buildings in Manhattan including the Chrysler Building, Flatiron, and One World Trade Center.",
    location: "New York City, USA",
    price: 55,
    imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80",
    category: "City Tours",
    duration: "3 hours",
    maxGuests: 15,
    userId: "user-11",
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-02-28"),
    author: {
      id: "user-11",
      name: "NYC Architecture Tours",
      email: "tours@nycarch.com",
    },
  },
  {
    id: "12",
    title: "Hot Air Balloon Ride over Cappadocia",
    description:
      "Float above the fairy chimneys and unique rock formations of Cappadocia at sunrise. This breathtaking experience offers panoramic views of one of Turkey's most spectacular landscapes. Includes champagne celebration and certificate. Truly a once-in-a-lifetime adventure!",
    location: "Cappadocia, Turkey",
    price: 220,
    imageUrl: "https://images.unsplash.com/photo-1515216326473-d685c48b39dc?w=800&q=80",
    category: "Adventure",
    duration: "3 hours",
    maxGuests: 16,
    userId: "user-12",
    createdAt: new Date("2024-02-27"),
    updatedAt: new Date("2024-02-27"),
    author: {
      id: "user-12",
      name: "Cappadocia Balloons",
      email: "fly@cappadociaballoons.com.tr",
    },
  },
];
